name: CI
on:
  push:
    branches:
      - main
      - master
      - '*v'
      - '*'
  pull_request:
    branches:
      - '*'
      - '**'
jobs:
  test:
    name: 'Ruby: ${{ matrix.ruby-version }}'
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7', '3.0', 'truffleruby', 'jruby']
        allow-failure: [false]
        frozen-string: [true]
        include:
          - ruby-version: 'head'
            allow-failure: true
            frozen-string: true
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        env:
          BUNDLE_WITHOUT: documentation
      - run: echo "{RUBYOPT}={--enable-frozen-string-literal}" >> $GITHUB_ENV
        if: ${{ matrix.frozen-string }}
      - run: bundle exec rake test --trace
        env:
          RUBYARCHDIR: './lib'
